# Generated by Django 5.0.1 on 2024-01-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_confirmation',
            field=models.CharField(choices=[("KO'RIBCHIQILMOQDA", "KO'RIBCHIQILMOQDA"), ('TAYORLANMOQDA,', 'TAYORLANMOQDA'), ('TAYOR', 'TAYOR')], default="KO'RIBCHIQILMOQDA", max_length=50),
        ),
    ]
